include: ['.htaccess', 'dist', 'docs', 'dist/_base*.js']
exclude:
  [
    'src',
    'node_modules',
    'types',
    'test',
    '.gitignore',
    '.npmrc',
    '.prettierignore',
    '.prettierrc',
    'package.json',
    'tsconfig.json',
    'vite.config.js'
  ]
